#!/bin/bash

#==================================================================================================================================#
# This file will get all resources/services, commands/subcommands and options from aws help into files folder #
#==================================================================================================================================#

mkdir -p files
mkdir -p files/services_commands
mkdir -p files/options

#=========== Step-01 ============#
# Get all aws services.
path="./files/all_services"
## Save aws documentation in file.
aws help | col -b > $path	
## Gran only available services.
echo "$(awk '/AVAILABLE SERVICES/{p=1};/SEE ALSO/{p=0};p' $path)" > $path    
## Remove whitespaces.
echo "$(awk '{$1=$1}1' $path)" > $path
## Grab only lines start with o.
echo "$(awk '$1 ~ /^o/ { print }' $path)" > $path
## Delete "0 " from start of a line
echo "$(awk '{ gsub(/o /,""); print }' $path)" > $path

## check all services
echo "from $path"
cat $path
#=========== ======= ============#


#=========== Step-02 ============#
# Get all commands
for service in $(cat $path);
do
	sub_path="./files/services_commands/$service"
	aws $service help | col -b > $sub_path
	echo "$(awk '/AVAILABLE COMMANDS/,EOF' $sub_path)" > $sub_path
	echo "$(awk '{$1=$1}1' $sub_path)" > $sub_path
	echo "$(awk '$1 ~ /^o/ { print }' $sub_path)" > $sub_path
	echo "$(awk '{ gsub(/o /,""); print }' $sub_path)" > $sub_path
	# check
	echo $sub_path
	echo "==================================================="
	echo "$(cat $sub_path)"
	echo "==================================================="
done
#=========== ======= ============#


#=========== Step-03 ============#
# Get all options
for service in $(ls -1 ./files/services_commands);
do
	mkdir -p ./files/options/$service
	for command in $(cat ./files/services_commands/$service);
	do
		path="./files/options/$service/$command"
		aws $service $command help | col -b > $path
		# Grab text between "SYNOPSIS" and "OPTIONS"
		echo "$(awk '$0=="SYNOPSIS" {p=1}; p; $0=="OPTIONS" {p=0}' $path)" > $path
		# Delete all whitespaces from start of each line
		echo "$(awk '{$1=$1}1' $path)" > $path
		# Remove "[|]" chars 
		echo "$(cat $path | tr -d "[|]")" > $path
		# Remove all lines that not start with -- 
		echo "$(awk '$1 ~ /^--/ { print }' $path)" > $path
		# Start new line when "--" apper
		sed -i $'s/--/\\\n&/g' $path
		# Delete all rest of the line after whitespace match
		sed -i $'s/ .*//' $path
		# Delete blank lines
		echo "$(awk 'NF > 0' $path)" > $path
		# check
		echo "=== option ==="
		cat $path
	done
done


